# Generated by Django 3.0.5 on 2020-04-13 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200413_1436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='isActive',
        ),
    ]
