# Generated by Django 3.0.5 on 2020-04-15 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_item_isactive'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='username',
            field=models.CharField(default='', max_length=100),
        ),
    ]
